name: srh-poc
channels:
- conda-forge
- default

dependencies:
- python=3
- numpy
- matplotlib
- pandas
- jupyterlab
- nb_black
- jupyterlab-git
- seaborn
- scipy
- pip

- pip:
  - jupyter-book
  - sphinx-thebe
