name: srh-poc
channels:
  - conda-forge
  - default

dependencies:
  - python=3
  - numpy
  - matplotlib
  - pandas
  - jupyterlab
  - nb_black
  - jupyter-book
  - jupyterlab-git
  - seaborn
  - scipy
