# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Kapitel 000
author: ixians
copyright: "2022" 
logo: _img/srh_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: CLT_poc.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ../Literaturverzeichnis.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    
# Information about where the book exists on the web
repository:
  url: https://github.com/ixianslab/srh-data-science  # Online location of your book
  #path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: True
  use_repository_button: true

launch_buttons:
  binderhub_url: "https://mybinder.org" 
  notebook_interface: "classic" #"jupyterlab"
  thebe: true
  
  
